server:
  port: 8090

spring:
  application:
    name: playground-api-gateway


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/


zuul:
  routes:
    msa-user-api:
      path: /api/user/**
    game-user-api:
      path: /api/game/**