server:
  port: 8095

spring:
  datasource:
    url: jdbc:mysql://localhost:60012/user_authentication
    username: root
    password: Passw0rd!
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  oauth2:
    client:
      client-id: auth_id
    client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key